[package]
name = "nova-reta-vortaro"
version = "0.1.0"
authors = ["Bat' <baptiste@gelez.xyz>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "*"
serde_json = "*"
markdown = { git = "https://github.com/johannhof/markdown.rs.git" }

[dependencies.rocket_contrib]
version = "0.3.6"
default-features = false
features = ["tera_templates", "json"]

[dependencies.diesel]
version = "0.99"
default-features = false
features = ["postgres", "uuid", "chrono"]
